### ISSUE TITLE
Server Crash due to Fragmentation when a client connects with a large quantity of replicated entities

### ISSUE THREAD

**Issue by bryvin** [cBournhonesque/lightyear#241] opened 2024-04-13 21:16 UTC
Hi,

I was stress testing the bullet spawn demo and spawned roughly 2800 bullets/balls and iteratively connecting new clients every 250 bullets or so.

When I reached around 2800 the server crashed when a new client tried to join. I also experienced this same problem even when not trying to connect _new_ clients but spawning too many bullets/balls at the same time.

Is this a bug with the fragmentation or is there a way to batch updates so that all of the world objects are not spawned in 1 frame?

![image](https://github.com/cBournhonesque/lightyear/assets/5969300/541c1f7c-574a-493a-9310-0b90d9f3a48f)

```
2024-04-13T21:07:22.572916Z  INFO lightyear::server::connection: New connection from id: Netcode(7)
thread 'Compute Task Pool (6)' panicked at lightyear\src\packet\packet_manager.rs:73:9:
packet = Packet { header: PacketHeader { packet_type: DataFragment, packet_id: PacketId(1114), last_ack_packet_id: PacketId(4), ack_bitfield: 15, tick: Tick(23941) }, data: Fragmented(FragmentedPacket { channel_id: 0, fragment: FragmentData { message_id: MessageId(2), tick: None, fragment_id: 15, num_fragments: 16, bytes: b"\0\0\0\xc4\x102\0\0\xd0\x0f\0\0\xe0\x0f\0\0\xc0\x0f\0\0\xe0\x8fIg\xc9\xe5\x90\x93\xf9~\x10\0\0\0\0\0\0\0\0\0\0\0\xc0p\xf2\xce\xef1\x7f\xcb\x0f\0\0\xe0\x0f\0\0\xe0\x0f\0\0\xe0\xcf\xf0\x01\0\0\x01\0\0\01\x84\x0c\0\0\xf4\x03\0\0\xf8\x03\0\0\xf0\x03\0\0\xf8cr\x05n9T\xeb10\x04\0\0\0\0\0\0\0\0\0\0\0\x90\xa9W\xf1k;\xfd\xf4\x03\0\0\xf8\x03\0\0\xf8\x03\0\0\xf8s|\0\0@\0\0\0@\x0c!\x03\0\0\xfd\0\0\0\xfe\0\0\0\xfc\0\0\0\xfe\x98\x88\x1dZ\x0e!\x83\x18\x0b\x01\0\0\0\0\0\0\0\0\0\0\0\xb8\xdb\x87\xfc\x12\x01\x19\xfd\0\0\0\xfe\0\0\0\xfe\0\0\0\xfe,\x1f\0\0\x10\0\0\0\x10C\xc8\0\0@?\0\0\x80?\0\0\0?\0\0\x80?&a\x05\x96Cf\x80VC\0\0\0\0\0\0\0\0\0\0\0\0\x07\xb3\xee\xbe\x04zb?\0\0\x80?\0\0\x80?\0\0\x80?\xcf\x07\0\0\x04\0\0\0\xc4\x102\0\0\xd0\x0f\0\0\xe0\x0f\0\0\xc0\x0f\0\0\xe0\x8f\t\xc7\x88\xe5\x10b\xd8\xc7\x10\0\0\0\0\0\0\0\0\0\0\0@\"\xa2\xc2\xef\xc6\xd1\xd5\x0f\0\0\xe0\x0f\0\0\xe0\x0f\0\0\xe0\xcf\xf4\x01\0\0\x01\0\0\01\x84\x0c\0\0\xf4\x03\0\0\xf8\x03\0\0\xf0\x03\0\0\xf8cB\x1c\x1c9T\xccm9\x04\0\0\0\0\0\0\0\0\0\0\0\0\x17\xa0\xeb[$\xe8\xf6\x03\0\0\xf8\x03\0\0\xf8\x03\0\0\xf8s}\0\0@\0\0\0@\x0c!\x03\0\0\xfd\0\0\0\xfe\0\0\0\xfc\0\0\0\xfe\x98\xec'\xd8\r\xa1\xeeX\x0e\x01\0\0\0\0\0\0\0\0\0\0\0\x9c\x1f\x83\xfa^3\xcc\xfd\0\0\0\xfe\0\0\0\xfe\0\0\0\xfel\x1f\0\0\x10\0\0\0\x10C\xc8\0\0@?\0\0\x80?\0\0\0?\0\0\x80?&F\x15\xf2BfV\x96C\0\0\0\0\0\0\0\0\0\0\0\0\xcc\x02\xf4\xbd,-~?\0\0\x80?\0\0\x80?\0\0\x80?\xdf\x07\0\0\x04\0\0\0\xc4\x102\0\0\xd0\x0f\0\0\xe0\x0f\0\0\xc0\x0f\0\0\xe0\x8f\xc9~\x82\xdd\x10\xea\x8e\xe5\x10\0\0\0\0\0\0\0\0\0\0\0\xc0\xf91\xa8\xef5\xc3\xdc\x0f\0\0\xe0\x0f\0\0\xe0\x0f\0\0\xe0\xcf\xf8\x01\0\0\x01\0\0\01\x84\x0c\0\0\xf4\x03\0\0\xf8\x03\0\0\xf0\x03\0\0\xf8cbT!/dfe9\x04\0\0\0\0\0\0\0\0\0\0\0\xc0,@\xdf\xcb\xd2\xe2\xf7\x03\0\0\xf8\x03\0\0\xf8\x03\0\0\xf8s~\0\0@\0\0\0@\x0c!\x03\0\0\xfd\0\0\0\xfe\0\0\0\xfc\0\0\0\xfe\x98\xf4\xdbt\x0c\x95\xc8[\x0e\x01\0\0\0\0\0\0\0\0\0\0\0T\x13\xee\xf8\x1e\xaf\xee\xfd\0\0\0\xfe\0\0\0\xfe\0\0\0\xfe\xac\x1f\0\0\x10\0\0\0\x10C\xc8\0\0@?\0\0\x80?\0\0\0?\0\0\x80?&\x0c\x14PB\xd0\xef\x96C\0\0\0\0\0\0\0\0\0\0\0\0\xe9\xba\x81<\xc8\xf7\x7f?\0\0\x80?\0\0\x80?\0\0\x80?\xef\x07\0\0\x04\0\0\0\xc4\x102\0\0\xd0\x0f\0\0\xe0\x0f\0\0\xc0\x0f\0\0\xe0\x8f\t1\xd48\xd0\x9c\xd0\xe5\x10\0\0\0\0\0\0\0\0\0\0\0\0r\xc4t\x8f\xc1\xa8\xdf\x0f\0\0\xe0\x0f\0\0\xe0\x0f\0\0\xe0\xcf\xfc\x01\0\0\x01\0\0\01\x84\x0c\0\0\xf4\x03\0\0\xf8\x03\0\0\xf0\x03\0\0\xf8cRNM.|ik9\x04\0\0\0\0\0\0\0\0\0\0\0\0H\x8e\xe9C\x1cE\xf7\x03\0\0\xf8\x03\0\0\xf8\x03\0\0\xf8s\x7f\0\0@\0\0\0@\x0c!\x03\0\0\xfd\0\0\0\xfe\0\0\0\xfc\0\0\0\xfe\x98`\xb0\xee\n\x83\x14Y\x0e\x01\0\0\0\0\0\0\0\0\0\0\0\x18\xc8,\xfa`n\xd9\xfd\0\0\0\xfe\0\0\0\xfe\0\0\0\xfe\xec\x1f\0\0\x10\0\0\0\x10C\xc8\0\0@?\0\0\x80?\0\0\0?\0\0\x80?&\xf9\xc7\x91\xc3\xe0\x86\x96C\0\0\0\0\0\0\0\0\0\0\0\0\xe8N\xea>\xbf\x9ec?\0\0\x80?\0\0\x80?\0\0\x80?\xff\x07\0\0\x04\0\0\0\xc4\x102\0\0\xd0\x0f\0\0\xe0\x0f\0\0\xc0\x0f\0\0\xe0\x8fI\x9dy\xd2\xb03\xab\xe5\x10\0\0\0\0\0\0\0\0\0\0\0@22\xb2O\x9d\xdf\xda\x0f\0\0\xe0\x0f\0\0\xe0\x0f\0\0\xe0\xcf", priority: 1.0 }, packet: SinglePacket { data: {0: [], 1: [SingleData { id: Some(MessageId(29)), tick: None, bytes: b"\x04\0\0\0\0\0\0\0\xd4\xadK\x04\0\0\0\x01\0\0\0\"\0\0\0\0\0\04C\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x80\xbf.\xbd;\xb3\0\0\x80?\0\0\x80?\0\0\x80?", priority: 11.0 }], 2: [SingleData { id: Some(MessageId(5)), tick: None, bytes: b"\x17\00\xaa-\00\xaa-\0\0", priority: 1.0 }]} } }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `lightyear::server::networking::send<bullet_prespawn::protocol::myprotocol_module::MyProtocol>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `C:\Users\bob\dev\lightyear\target\debug\bullet_prespawn.exe server` (exit code: 101)
```

**Comment by cBournhonesque** [comment] 2024-04-13 23:24
Hi, thank you for the report!

This does look like a bug with the fragmentation logic; [this assert](https://github.com/cBournhonesque/lightyear/blob/0.13.0/lightyear/src/packet/packet_manager.rs#L73) should never be false. There must be somewhere in the code where I'm not counting the bits written correctly; I will look into that!


Some more comments on your example:
1) In this example we are sending all the bullets in a **single individual message** because they are part of the same `ReplicationGroup`. I need to make it clearer in the docs/book (https://cbournhonesque.github.io/lightyear/book/concepts/advanced_replication/replication_logic.html#invariants) but basically most updates/messages will be sent as different messages. Only entities that are part of the same `ReplicationGroup` will be sent as a single message. (this is important for cases where you need a guarantee that all the updates for a group of entities will arrive exactly at the same time; for example here since we are running client-prediction on all the bullets, so they all need to arrive at the same time)

So you could try splitting the bullets into different `ReplicationGroups`, but this will probably break the client-prediction a bit.

2) 

> is there a way to batch updates so that all of the world objects are not spawned in 1 frame?

You also can set a **maximum bandwidth** for your data transfer: [book](https://cbournhonesque.github.io/lightyear/book/concepts/advanced_replication/bandwidth_management.html). Then the server will send messages until the bandwidth is reached. This will probably not help in your case, because as I mentioned above all your updates are grouped into a single message because of the `ReplicationGroup`

3) I haven't looked too much into optimization/performance since I'm focusing on ergonomics/features first, but that's definitely something that I want to focus on in the feature. I need to add more benchmarks/stress-tests

**Comment by cBournhonesque** [comment] 2024-04-24 21:40
I've tried generating a bunch of packets between size 1000 bytes to 100000 bytes but I haven't been able to reproduce this.
it's probably happening when the PacketHeader has reached the maximum size, or when there are multiple channels?

I'll keep an eye on this

**Comment by cBournhonesque** [comment] 2024-08-13 15:08
This should be fixed with the refactoring of the fragmentation code

**Closed by cBournhonesque** 2024-08-13 15:08 UTC
Labels: C-Bug, P-High, A-Replication
